name: Workflows with large secrets

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Hello world action
      with: # Set the secret as an input
            project_id: ${{ secrets.GS_PROJECT_ID }}
            private_key_id: ${{ secrets.GS_PRIVATE_KEY_ID }}
            private_key: ${{ secrets.GS_PRIVATE_KEY }}
            client_email: ${{ secrets.GS_CLIENT_EMAIL }}
            client_id: ${{ secrets.GS_CLIEND_ID }}
            client_x509_cert_url: ${{  secrets.GS_CLIEND_X509_CERT_URL }}
        
